version: 2
updates:
  - package-ecosystem: maven
    target-branch: "develop"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
    open-pull-requests-limit: 10
    ignore:
    - dependency-name: org.apache.derby:derby
      versions:
      - "> 10.14.2.0"
  - package-ecosystem: "github-actions"
    target-branch: "develop"
    directory: "/"
    schedule:
      interval: "daily"
